todo/config/routes.rb
Rails.application.routes.draw do
  root 'main#home'

	
	resources :tasks, except: [:index]

end

todo/app/models/task.rb
class Task < ActiveRecord::Base
end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/main_controller.rb
class MainController < ApplicationController
	def home
		@tasks = Task.all
	end
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@task = Task.new
		render :task_form_modal
	end

	def create
		Task.create(task_params)
		@tasks = Task.all
		render :finish_modal_action
	end

	def show
		@task = Task.find(params[:id])
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		@tasks = Task.all
		render :finish_modal_action
	end

	def edit
		@task = Task.find(params[:id])
		render :task_form_modal
	end

	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
		@tasks = Task.all
		render :finish_modal_action
	end

	private
	def task_params
		params.require(:task).permit(:title, :note, :completed)
	end
end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/helpers/main_helper.rb
module MainHelper
end

todo/app/helpers/tasks_helper.rb
module TasksHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row-fluid">
		<div class="span10 offset1">
			<div class="hero-unit text-center">
				<h1> Todo app </h1>
				<%= link_to 'New Task', new_task_path, class: 'btn btn-primary', remote: true %>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

todo/app/views/main/home.html.erb
<div class="taskList container">
	<%= render partial: 'tasks/task_list', locals: {tasks: @tasks} %>
</div>
<!-- modal is for creating or modifying a task-->
<div id="modal" class="modal fade"</div>

todo/app/views/tasks/_task_form.html.erb
<div class="modal-header">
	<h1><%= task.new_record? ? 'New Task' : 'Edit Task: ' + task.title %></h1>
	<%= simple_form_for @task, class: "clearfix", remote: true do |form| %>
		<div class="modal-body">
			<%= form.input :title %>
			<%= form.input :note %>
			<%= form.input :completed %>
		</div>
		<div class="modal-footer">
			<%= form.submit 'Save', class: 'btn btn-primary'%>
		</div>
		<% end %>
</div>

todo/app/views/tasks/_task_list.html.erb
<div>
	<% if @tasks.empty?%>
		<span class="text-warning">There are no tasks</span>
	<% else %>
		<div class="list-group tasks">
			<% @tasks.each do |task| %>
				<%= link_to task_path(:id => task.id), remote: true do %>
					<button type="button" class="list-group-item text-left <%= 'disabled' if task.completed %> task">
						<%if task.completed %> 
							<span class="badge">
								Completed
							</span>
						<% end %>
						<div class=taskTitle>
							<%= task.title %>:
						</div>
						<div class="taskContents">
							<div class="taskDescription">
								<%= task.note %>
							</div>
							<div class="taskCompleted">
								completed = <%= task.completed %>
							</div>
						</div>
					</button>
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

todo/app/views/tasks/_task_modify.html.erb
<div class="modal-header">
	<h1>Modify Task</h1>
	<div>
		<%= link_to 'Delete Task', task_path(task), class: 'btn btn-primary modifyBtn', remote: true, method: :delete, data: {confirm: 'Delete task: ' + @task.title} %>
		<%= link_to 'Edit Task', edit_task_path, class: 'btn btn-primary modifyBtn', remote: true %>
	</div>
</div>

todo/app/views/tasks/finish_modal_action.js.erb
$('#modal').modal('hide');
$('.taskList').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');

todo/app/views/tasks/show.js.erb
modifyTaskModal = $('#modal');
modifyTaskModal.html('<%= j(render partial: 'task_modify', locals: {task: @task}) %>');
modifyTaskModal.modal('show');

todo/app/views/tasks/task_form_modal.js.erb
newTaskModal = $('#modal');
newTaskModal.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
newTaskModal.modal('show');